from .config import CfgNode as CN

_K = CN()

kfg = _K

_K.POINTS = 'POINTS'
_K.POINTS_LABELS = 'POINTS_LABELS'
_K.TREES = 'TREES'
_K.NORMALS = 'NORMALS'
_K.LABELS = 'LABELS'
_K.MASKS = 'MASKS'
_K.FEATS = 'FEATS'
_K.LOGITS = 'LOGITS'

_K.CLOUD_INDEX = 'CLOUD_INDEX'
_K.INPUT_INDEX = 'INPUT_INDEX'