DATASET:
  NAME: 'ModelNet40Cls'

DATALOADER:
  TRAIN_BATCH_SIZE: 16
  TEST_BATCH_SIZE: 16
  NUM_WORKERS: 4
  DATA_ROOT: './dataset'
  NUM_POINTS: 10000
  SUBSAMPLING: 0.02

AUG:
  SCALE_LOW: 0.6
  SCALE_HIGH: 1.4
  NOISE_STD: 0.002
  NOISE_CLIP: 0.05
  TRANSLATE_RANGE: 0.0
  X_ANGLE_RANGE: 3.141592653589793
  Y_ANGLE_RANGE: 3.141592653589793
  Z_ANGLE_RANGE: 3.141592653589793
  NUM_VOTES: 10
  TEST_ROTATE: True

ENGINE:
  NAME: 'DefaultTrainer'
  BEST_METRICS: ['SO3-ACC@1']
  FP16: True
  
MODEL:
  META_ARCHITECTURE: 'ClsNet'
  INFEATS_DIM: 3
  NUM_CLASSES: 40
  DROP_PATH: 0.1

  STEM:
    NAME: 'EmptyStem'
    WIDTH: 36

  BACKBONE:
    NAME: 'ResNet'
    LAYERS: [1, 2, 2, 2, 2]
    DIMS: [72, 144, 288, 576, 1152]
    BTNK_RATIOS: [2, 2, 2, 2, 2]
    NPOINTS: [-1, 2048, 512, 128, 32 ]
    NSAMPLES: [ 20, 31, 38, 36, 34 ]
    RADIUS: 0.05
    SAMPLEDL: 0.02

  LA_TYPE:
    NAME: 'SPEMLP'
    FEAT_TYPE: 'query,n,n'
    NUM_MLPS: 1
    REDUCTION: 'top3'

  DOWN_SAMPLER:
    NAME: 'MaxPoolDS'

  HEAD:
    NAME: 'ClsHead3Layer'

  GLOBAL_POOLER:
    NAME: 'GlobalMaxPooler'
 
  RRI:
    NAME: 'RotInvRRISep'
    DIMS: [ 18 ]
    NSAMPLES: [ 50 ]
    NORM_LAST: True
    ACT_LAST: True

SOLVER:
  NAME: 'SGD'
  EPOCH: 300
  CHECKPOINT_PERIOD: 1
  EVAL_PERIOD: 5
  VOTE_START: 150
  DENSE_EVAL_EPOCH: 250
  BASE_LR: 0.05
  WEIGHT_DECAY: 0.0002
  WEIGHT_DECAY_NORM: 0.0002
  MOMENTUM: 0.9
  ALPHA: 0.99
  BETAS: [0.9, 0.999]
  WRITE_PERIOD: 20
  AUTO_LR: True

LR_SCHEDULER:
  NAME: 'WarmupCosineLR'
  WARMUP_EPOCH: 5

LOSSES:
  NAMES: ['LabelSmoothing']
  LABELSMOOTHING: 0.2

INFERENCE:
  NAME: 'ClsEvaluator'