DATASET:
  NAME: 'S3DISSeg'

DATALOADER:
  TRAIN_BATCH_SIZE: 8
  TEST_BATCH_SIZE: 8
  NUM_WORKERS: 1
  DATA_ROOT: './dataset'
  NUM_POINTS: 15000
  SUBSAMPLING: 0.04
  IN_RADIUS: 2.0
  NUM_STEPS: 2000
  COLOR_DROP: 0.2
  SHUFFLE: False

AUG:
  SCALE_LOW: 0.7
  SCALE_HIGH: 1.3
  NOISE_STD: 0.001
  NOISE_CLIP: 0.05
  TRANSLATE_RANGE: 0.0
  X_ANGLE_RANGE: 0.0
  Y_ANGLE_RANGE: 0.0
  Z_ANGLE_RANGE: 3.1415926
  AUGMENT_SYMMETRIES: [1, 0, 0]
  NUM_VOTES: 1
  TEST_ROTATE: False

ENGINE:
  NAME: 'DefaultTrainer'
  BEST_METRICS: ['mIoU']
  FP16: True

MODEL:
  META_ARCHITECTURE: 'SegNet'
  INFEATS_DIM: 4
  NUM_CLASSES: 13
  DROP_PATH: 0.1

  STEM:
    NAME: 'ConvStem'
    WIDTH: 72
    FEAT_TYPE: 'concat'

  BACKBONE:
    NAME: 'ResNet'
    LAYERS: [1, 2, 2, 2, 2]
    DIMS: [144, 288, 576, 1152, 2304]
    BTNK_RATIOS: [2, 2, 2, 2, 2]
    NPOINTS: [-1, 4096, 1152, 304, 88 ]
    NSAMPLES: [ 26, 31, 38, 41, 39 ]
    RADIUS: 0.1
    SAMPLEDL: 0.04

  LA_TYPE:
    NAME: 'SPEMLP'
    FEAT_TYPE: 'pool,n,n'
    NUM_MLPS: 1
    REDUCTION: 'top3'

  DOWN_SAMPLER:
    NAME: 'MaxPoolDS'

  HEAD:
    NAME: 'SceneSegHead'

  GLOBAL_POOLER:
    NAME: 'GlobalMaxPooler'
 

SOLVER:
  NAME: 'SGD'
  EPOCH: 600
  CHECKPOINT_PERIOD: 20
  EVAL_PERIOD: 20
  VOTE_START: 580
  DENSE_EVAL_EPOCH: 580
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.001
  WEIGHT_DECAY_NORM: 0.001
  MOMENTUM: 0.98
  ALPHA: 0.99
  BETAS: [0.9, 0.999]
  WRITE_PERIOD: 20
  AUTO_LR: True

LR_SCHEDULER:
  NAME: 'StepLR'
  STEP_SIZE: 1
  GAMMA: 0.9885531

LOSSES:
  NAMES: ['MaskedCrossEntropy']

INFERENCE:
  NAME: 'S3DISEvaluator'
