DATASET:
  NAME: 'ShapeNetPartSeg'

DATALOADER:
  TRAIN_BATCH_SIZE: 16
  TEST_BATCH_SIZE: 16
  NUM_WORKERS: 4
  DATA_ROOT: './dataset'
  NUM_PARTS: [4, 2, 2, 4, 4, 3, 3, 2, 4, 2, 6, 2, 3, 3, 3, 3]
  NUM_POINTS: 2048

AUG:
  SCALE_LOW: 0.7
  SCALE_HIGH: 1.3
  NOISE_STD: 0.001
  NOISE_CLIP: 0.05
  TRANSLATE_RANGE: 0.0
  X_ANGLE_RANGE: 3.141592653589793
  Y_ANGLE_RANGE: 3.141592653589793
  Z_ANGLE_RANGE: 3.141592653589793
  NUM_VOTES: 10
  TEST_ROTATE: True

ENGINE:
  NAME: 'DefaultTrainer'
  BEST_METRICS: ['SO3-mmpIoU']
  FP16: True

MODEL:
  META_ARCHITECTURE: 'SegNet'
  INFEATS_DIM: 3
  NUM_CLASSES: 16
  DROP_PATH: 0.1

  STEM:
    NAME: 'EmptyStem'
    WIDTH: 36

  BACKBONE:
    NAME: 'ResNet'
    LAYERS: [1, 2, 2, 2, 2]
    DIMS: [72, 144, 288, 576, 1152]
    BTNK_RATIOS: [2, 2, 2, 2, 2]
    NPOINTS: [-1, 1280, 768, 192, 64 ]
    NSAMPLES: [ 11, 25, 37, 36, 33 ]
    RADIUS: 0.05
    SAMPLEDL: 0.02

  LA_TYPE:
    NAME: 'SPEMLP'
    FEAT_TYPE: 'pool,n,n'
    NUM_MLPS: 1
    REDUCTION: 'top3'

  DOWN_SAMPLER:
    NAME: 'MaxPoolDS'

  HEAD:
    NAME: 'MultiPartSegHead'

  GLOBAL_POOLER:
    NAME: 'GlobalAvgPooler'
 

SOLVER:
  NAME: 'AdamW'
  EPOCH: 300
  CHECKPOINT_PERIOD: 1
  EVAL_PERIOD: 5
  VOTE_START: 150
  DENSE_EVAL_EPOCH: 250
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.00001
  WEIGHT_DECAY_NORM: 0.00001
  MOMENTUM: 0.9
  ALPHA: 0.99
  BETAS: [0.9, 0.999]
  WRITE_PERIOD: 20
  AUTO_LR: False

LR_SCHEDULER:
  NAME: 'WarmupCosineLR'
  WARMUP_EPOCH: 5

LOSSES:
  NAMES: ['MultiShapeCrossEntropy']

INFERENCE:
  NAME: 'SegRotateEvaluator'